apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ .Release.Name }}
  labels:
{{ include "prometheus-postgres-exporter.labels" . | indent 4 }}
spec:
  podTargetLabels:
    {{- keys .Values.additionalLabels | toYaml | nindent 4 }}
  podMetricsEndpoints:
    - port: metrics
      {{- with .Values.scrape.timeout }}
      scrapeTimeout: {{ . | quote }}
      {{- end }}
      {{- with .Values.scrape.interval }}
      interval: {{ . | quote }}
      {{- end }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
{{ include "prometheus-postgres-exporter.selector" . | indent 6 }}
