image:
  repository: bitnami/postgres-exporter
  tag: 0.9.0
  pullPolicy: IfNotPresent

auto_discover_databases: true
rds: false
# Change this to 'true' if it's an azure rds instance
# because hostname need to be added at the end of username.
# Note that you cannot use secret for username in this case
# If azure=true, you cannot use 'usernameSecret'
azure: false
pg_stat_statements: true
pg_stat_user_tables: true
light_threshold: 0
pg_client_connections: true
pg_table_size: true
pg_table_size_threshold: 100000
version: "12"
# Use either 'username' or 'usernameSecret'
username: postgres
#usernameSecret:
#  name: secret-name
#  key: user

# Use either 'password' or 'passwordSecret'
password: pgpass
#passwordSecret:
#  name: secret-name
#  key: pass

exclude_databases: "template0,template1,rdsadmin,azure_maintenance"
master: master:5432/postgres?sslmode=require
replicas:
  - replica0:5432/postgres?sslmode=require
  - replica1:5432/postgres?sslmode=require
  - replica2:5432/postgres?sslmode=require
additionalLabels:
  site: pg-12-prod
  line: prod

scrape: {}
  #timeout: 10s
  #interval: 30s

dashboard: default
